laike9m/Python-Type-Challenges

pdm.lock, pyproject.toml, views/utils.py
Signed-off-by: Frost Ming <me@frostming.com>
So that users can run mypy locally with consistent behavior
=> feat: move mypy config to pyproject.toml

templates/challenge.html, views/views.py
Signed-off-by: Frost Ming <me@frostming.com>
Fix #2
Fix #13
=> feat: show python version at the top

templates/challenge.html
Signed-off-by: Manjusaka <me@manjusaka.me>
=> fix: Make sure indentation in existing code and code editor are consistent

templates/base.html, templates/challenge.html, templates/components/darkmode.html, templates/index.html, views/views.py
Now CodeMirror editor can automatically set dark theme in dark mode!
=> feat(ui): add dark theme for editor and adjust some ui details

templates/challenge.html, views/views.py
Add some confetti effect when test cases passed. Make challenge be more funny.
=> feat: Add confetti effect and return JSON response for challenge result

templates/challenge.html
=> feat(ui): add reset button for code editor

challenges/intermediate-callable/solution.py, challenges/intermediate-class-var/solution.py, challenges/intermediate-decorator/question.py, challenges/intermediate-decorator/solution.py, challenges/intermediate-generic-with-constraints/solution.py, challenges/intermediate-generic/solution.py, challenges/intermediate-instance-var/solution.py, challenges/intermediate-literal/solution.py, challenges/intermediate-union/solution.py
@laike9m Please help review. Thanks.
#19
=> add intermediate solutions

challenges/basic-variable/solution.py, challenges/extreme-constructor-parameter/question.py, challenges/extreme-constructor-parameter/solution.py, challenges/intermediate-class-var/question.py, challenges/intermediate-class-var/solution.py, pyproject.toml
Signed-off-by: Frost Ming <me@frostming.com>
=> fix: minor adjustment for some solutions

challenges/advanced-callable-protocol/solution.py, challenges/advanced-generic-param/solution.py, challenges/advanced-overload/solution.py, challenges/advanced-protocol/solution.py, challenges/advanced-recursive/solution.py, challenges/advanced-self/solution.py, challenges/advanced-typeguard/solution.py
=> add advanced solutions

challenges/advanced-overload-generic/question.py, challenges/advanced-overload-literal/solution.py, challenges/extreme-constructor-parameter/question.py, challenges/intermediate-generic/solution.py, tests/test_identical.py
=> Add a test to verify the test code in question and solution are identical

challenges/advanced-paramspec/question.py, challenges/advanced-paramspec/solution.py
Signed-off-by: Frost Ming <me@frostming.com>
=> new challenge: advanced paramspec

challenges/basic-any/question.py
This PR update the "any" question to require code changes in order to pass, more discussions can be found at #67
=> Enhance: update the "any" question to require code changes in order to pass

challenges/basic-any/hints.md, challenges/intermediate-generic2/hints.md, docs/Contribute.md, docs/Development.md, pdm.lock, pyproject.toml, requirements.txt, templates/challenge.html, tests/assets/challenges/basic-foo-hints/hints.md, tests/assets/challenges/basic-foo-hints/question.py, tests/assets/challenges/basic-foo/question.py, tests/conftest.py, tests/test_challenge.py, tests/test_utils.py, views/challenge.py, views/utils/text.py, views/views.py
- Support an optional hint message for challenges
- Update contrib.md to demonstrate adding hints
- Added 2 hints: `basic-any`, `intermediate-generic2`
=> Support Hints

challenges/advanced-buffer/hints.md, challenges/advanced-callable-protocol/hints.md, challenges/advanced-callable-protocol/question.py, challenges/advanced-callable-protocol/solution.py, challenges/advanced-decorator/hints.md, challenges/advanced-decorator/solution.py, challenges/advanced-descriptor/hints.md, challenges/advanced-descriptor/question.py, challenges/advanced-descriptor/solution.py, challenges/advanced-forward/hints.md, challenges/advanced-generator/hints.md, challenges/advanced-generic-class/hints.md, challenges/advanced-never/hints.md, challenges/advanced-overload/hints.md, challenges/advanced-paramspec/hints.md
Add hints for most of the advanced challenges.
=> Add hints for most of the advanced challenge.

challenges/intermediate-await/hints.md, challenges/intermediate-await/solution.py, challenges/intermediate-callable/hints.md, challenges/intermediate-callable/solution.py, challenges/intermediate-class-var/hints.md, challenges/intermediate-decorator/hints.md, challenges/intermediate-generic/hints.md, challenges/intermediate-generic2/hints.md, challenges/intermediate-instance-var/hints.md, challenges/intermediate-literal/hints.md, challenges/intermediate-literalstring/hints.md, challenges/intermediate-self/hints.md, challenges/intermediate-self/solution.py, challenges/intermediate-typed-dict/hints.md, challenges/intermediate-typed-dict2/hints.md, challenges/intermediate-typed-dict3/hints.md
Add hints for most of the intermediate challenges.
Some hints might be not good enough, please feel free to modify them. @laike9m
=> Add hints for most of the intermediate challenges

challenges/intermediate-self/hints.md
Update challenges/intermediate-self/hints.md: Fix typo.
=> Update challenges/intermediate-self/hints.md: Fix typo

challenges/advanced-typeshed/question.py, challenges/advanced-typeshed/solution.py
`https://github.com/python/typeshed` ->
`https://github.com/python/typeshed/blob/main/stdlib/_typeshed/__init__.pyi`
---
Resolve #86
=> Update hint for advanced-typeshed

.gitignore, .pre-commit-config.yaml, pyproject.toml
=> Fix pre-commit ci

tests/conftest.py, tests/test_hints.py
Check if python docs links to English documentation
=> Add test for hints.md

templates/challenge.html, templates/components/challenge_sidebar.html
remove unnecessary x-axis scrollbar.
=> Remove x-axis scrollbar

challenges/extreme-constructor/solution.py, challenges/extreme-self-casting/solution2.py, pdm.lock, pyproject.toml
=> Replace black with ruff

templates/components/challenge_area.html
=> Remove old CodeMirrors when history load

templates/components/challenge_area.html, templates/components/challenge_sidebar.html
=> Support auto fold the challenge list on mobile

challenges/advanced-decorator/solution.py, challenges/advanced-overload-literal/solution.py, challenges/basic-typealias/solution.py, challenges/extreme-constructor/solution.py, challenges/intermediate-decorator/solution.py, challenges/intermediate-generic/solution.py, challenges/intermediate-generic2/solution.py, challenges/intermediate-generic3/solution.py
Some improvements for python 3.12:
- added some missing 3.12 solutions
- Made python 3.12 the default solution (not commented out)
- tried to be more consistent in comments for python versions
=> feat: unify solution for python 3.12

challenges/extreme-concatenate/hints.md
Add hints for the extreme concatenate problem (see #115 )
=> feat: add hints for extreme concatenate
